server:
  port: 8081

health:
  message: "Hello from user-service in LOCAL!"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

  # --- 로컬 Kafka (Docker Compose) 설정 ---
  cloud:
    function:
      definition: orderCreated
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orderCreated-in-0:
          destination: order-created
          group: user-service
        pointsFailed-out-0:
          destination: points-failed
          content-type: application/json

    kubernetes:
      config:
        enabled: false # K8s ConfigMap 읽기 끄기
      discovery:
        enabled: false # K8s Service Discovery 끄기

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: user-service