server:
  port: 8081

health:
  message: "Hello from user-service in LOCAL!"

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /user-h2-console

  # --- 로컬 Kafka (Docker Compose) 설정 ---
  cloud:
    function:
      definition: orderCreated
    stream:
      kafka:
        binder:
          brokers: localhost:9092 # ✅ localhost의 Kafka
      bindings:
        orderCreated-in-0:
          destination: order-created
          group: user-service
        pointsFailed-out-0:
          destination: points-failed
          content-type: application/json

    # --- ⛔️ K8s 기능 "끄기" ---
    kubernetes:
      config:
        enabled: false # ❗️ K8s ConfigMap 읽기 끄기
      discovery:
        enabled: false # ❗️ K8s Service Discovery 끄기

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: user-service